config/routes.rb
Rails.application.routes.draw do
  resources :space_explorers
  root 'space_explorers#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/space_explorer.rb
class SpaceExplorer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/space_explorers_controller.rb
class SpaceExplorersController < ApplicationController

  include SpaceExplorersHelper
  @api_uri = "https://anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/aa4e5e49-3abe-4ec6-861b-b1edc0508cd3/space/1.0.0/m"
  # before_action :set_space_explorer, only: [:show, :edit, :update, :destroy]

  # GET /space_explorers
  # GET /space_explorers.json
  def index

    resp= get_all_spaces()
    @space = resp=='err'? 'err' : resp['items'][0]
    @entries = get_all_entries(@space['sys']['id'])
    @entries_table_fieldnames = {'fields': ['title','summary',''],'sys':['createdAt','createdBy','updatedAt','updatedBy']}
    @assets_table_fieldnames = {'fields':  ['title', 'contentType', 'fileName', 'upload'], 'sys': ['createdAt', 'createdBy', 'updatedAt']}
    @assets = get_all_assets(@space['sys']['id'])
  end

  # GET /space_explorers/1
  # GET /space_explorers/1.json
  def show
    resp= get_all_spaces()
    @space = resp=='err'? 'err' : resp['items'][0]
    # @space = get_all_spaces()['items'][0]
    @entries = get_all_entries(params[:id])
    @entries_table_fieldnames = {'fields': ['title','summary',''],'sys':['createdAt','createdBy','updatedAt','updatedBy']}
    @assets_table_fieldnames = {'fields':  ['title', 'contentType', 'fileName', 'upload'], 'sys': ['createdAt', 'createdBy', 'updatedAt']}
    @assets = get_all_assets(params[:id])

  end

  # GET /space_explorers/new
  def new
    @space_explorer = SpaceExplorer.new
  end

  # GET /space_explorers/1/edit
  def edit
  end

  # POST /space_explorers
  # POST /space_explorers.json
  def create
    @space_explorer = SpaceExplorer.new(space_explorer_params)

    respond_to do |format|
      if @space_explorer.save
        format.html { redirect_to @space_explorer, notice: 'Space explorer was successfully created.' }
        format.json { render :show, status: :created, location: @space_explorer }
      else
        format.html { render :new }
        format.json { render json: @space_explorer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /space_explorers/1
  # PATCH/PUT /space_explorers/1.json
  def update
    respond_to do |format|
      if @space_explorer.update(space_explorer_params)
        format.html { redirect_to @space_explorer, notice: 'Space explorer was successfully updated.' }
        format.json { render :show, status: :ok, location: @space_explorer }
      else
        format.html { render :edit }
        format.json { render json: @space_explorer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /space_explorers/1
  # DELETE /space_explorers/1.json
  def destroy
    @space_explorer.destroy
    respond_to do |format|
      format.html { redirect_to space_explorers_url, notice: 'Space explorer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space_explorer
      @space_explorer = SpaceExplorer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_explorer_params
      params.fetch(:space_explorer, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/space_explorers_helper.rb
require 'uri'
require 'net/http'
require 'json'

module SpaceExplorersHelper
  API_uri = "https://anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/aa4e5e49-3abe-4ec6-861b-b1edc0508cd3/space/3.0.1/m"

  Test_uri="https://anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/aa4e5e49-3abe-4ec6-861b-b1edc0508cd3/space/2.0.0/m"

  def spaces_get(url)
    result = Net::HTTP.get_response(URI(url))
    return result
  end

  def get_all_spaces()
    full_url = API_uri + '/space'
    space_data = spaces_get(full_url)
    begin
      if space_data.is_a?(Net::HTTPSuccess) then
      return JSON.parse(space_data.read_body.as_json)
      else
        return 'err'
      end
    rescue
      return 'err'
    end
  end

  def get_space_by_id(id)
    full_url = API_uri + '/space/' + id.to_s
    space_data = spaces_get(full_url)
    begin
      if space_data.is_a?(Net::HTTPSuccess) then
      return JSON.parse(space_data.read_body.as_json)
      else
        return 'err'
      end
    rescue
      return 'err'
    end
  end

  def get_all_entries(space_id)
    full_url = API_uri+'/space/'+space_id.to_s+'/entries'
    entries_data = spaces_get(full_url)
    begin
      if entries_data.is_a?(Net::HTTPSuccess) then
      return JSON.parse(entries_data.read_body.as_json)
      else
        return 'err'
      end
    rescue
      return 'err'
    end
  end

  def get_user_by_id(user_id)
    full_url=API_uri+'/users/'+user_id.to_s
    user_data = spaces_get(full_url)
    begin
      if user_data.is_a?(Net::HTTPSuccess) then
      return JSON.parse(user_data.read_body.as_json)
      else
        return 'err'
      end
    rescue
      return 'err'
    end
  end

  def split_camel_casing(text)
    words_array = text.split /(?=[A-Z])/
    return words_array*" "
  end

  def get_all_assets(space_id)
    full_url = API_uri+'/space/'+space_id.to_s+'/assets'
    assets_data = spaces_get(full_url)
    begin
      if assets_data.is_a?(Net::HTTPSuccess) then
      return JSON.parse(assets_data.read_body.as_json)
      else
        return 'err'
      end
    rescue
      return 'err'
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceTheSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/space_explorers/_form.html.erb
<%= form_with(model: space_explorer, local: true) do |form| %>
  <% if space_explorer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space_explorer.errors.count, "error") %> prohibited this space_explorer from being saved:</h2>

      <ul>
      <% space_explorer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/space_explorers/_space.html.erb
<div class="row">
  <div class='col-xs'>

    <ul class="nav nav-pills flex-column">
      <% get_all_spaces()['items'].each do |entry|%>
      <li class="nav-item">

        <a class="nav-link" href="/space_explorers/<%=entry['sys']['id']%>"><%=entry['fields']['title']%></a>
      </li>

      <%end%>
    </ul>
  </div>
  <div class='col-xl'>
    <div class="card" id='div-main'>
      <div class="card-body">
        <p id="notice"><%= notice %></p>

        <h1><%=@space['fields']['title'] %></h1>
        <h6><%=@space['fields']['description'] %></h6>

        <div class="btn-group" role="group">
          <button class="btn btn-secondary" onclick="ShowEntries()" id="tab-entries">Entries</button>

          <button class="btn btn-secondary" onclick="ShowAssets()" id="tab-assets">Assets</button>
        </div>

        <div class="card pre-scrollable" id='div-entries'>
          <div class="card-body">
            <table class="table ">
              <thead>
                <tr>
                  <% @entries_table_fieldnames.values.each do |value|  %>
                  <%value.each do |val_index|%>
                  <th scope="col"><%= split_camel_casing(val_index).titleize%></th>
                  <%end%>
                  <%end%>
                </tr>
              </thead>
              <tbody>
                <%@entries['items'].each do |entry|%>
                <tr>
                  <% @entries_table_fieldnames.keys.each do |key|  %>
                  <%@entries_table_fieldnames[key].each do |val_index|%>
                  <td>
                    <%if (val_index=='createdBy' or val_index=='updatedBy') then%>
                    <%= get_user_by_id(entry[key.to_s][val_index])['fields']['name'] %>
                    <%else%>
                    <%= entry[key.to_s][val_index] %>
                    <%end%>
                  </td>

                  <%end%>
                  <%end%>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card pre-scrollable" id="div-assets">
          <div class="card-body">
            <table class="table">
              <thead>
                <tr>
                  <% @assets_table_fieldnames.values.each do |value|  %>
                  <%value.each do |val_index|%>
                  <%if (val_index=='upload') then%>
                  <%else%>
                  <th scope="col"><%= split_camel_casing(val_index).titleize%></th>
                  <%end%>
                  <%end%>
                  <%end%>
                </tr>
              </thead>
              <tbody>
                <%@assets['items'].each do |asset|%>
                <tr>
                  <% @assets_table_fieldnames.keys.each do |key|  %>
                  <%@assets_table_fieldnames[key].each do |val_index|%>
                  <%if (val_index=='upload') then%>
                  <%else%>
                  <td>
                    <%if (val_index=='fileName') then%>
                    <a href="<%= asset[key.to_s]['upload'] %>"><%= asset[key.to_s][val_index] %></a>
                    <%else%>

                    <%if (val_index=='createdBy' or val_index=='updatedBy') then%>
                    <%= get_user_by_id(asset[key.to_s][val_index])['fields']['name'] %>
                    <%else%>
                    <%= asset[key.to_s][val_index] %>
                    <%end%>
                    <%end%>

                  </td>
                  <%end%>
                  <%end%>
                  <%end%>
                </tr>
                <%end%>
              </tbody>
            </table>
          </div>
          <br>
        </div>
      </div>
      <!-- <div class="row"> -->
      <%# <%= link_to 'New Space Explorer', new_space_explorer_path %>
      <!-- </div> -->
    </div>
  </div>
</div>
<script>

  function ShowEntries(){
    $('#div-assets').hide();
    $('#div-entries').show();

  }
  function ShowAssets(){
    $('#div-entries').hide();
    $('#div-assets').show();

  }

  $(document).ready( function () {
    $('#div-assets').hide();
  });
</script>

app/views/space_explorers/edit.html.erb
<h1>Editing Space Explorer</h1>

<%= render 'form', space_explorer: @space_explorer %>

<%= link_to 'Show', @space_explorer %> |
<%= link_to 'Back', space_explorers_path %>

app/views/space_explorers/index.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs'>

      <ul class="nav nav-pills flex-column">
        <%unless get_all_spaces()=='err'%>
        <% get_all_spaces()['items'].each do |entry|%>
        <li class="nav-item">
          
          <a class="nav-link" href="/space_explorers/<%=entry['sys']['id']%>"><%=entry['fields']['title']%></a>
        </li>
        <%end%>

        <%end%>
      </ul>
    </div>
    <div class='col-xl'>
      <div class="card" id='div-main'>
        <div class="card-body">
          <p id="notice"><%= notice %></p>
          <%if get_all_spaces()=='err'%>
            <h6>We're having trouble loading spaces - please try again later</h6>
          <%else%>
          <h1><%=@space['fields']['title'] %></h1>
          <h6><%=@space['fields']['description'] %></h6>

          <div class="btn-group" role="group">
            <button class="btn btn-secondary active" onclick="ShowEntries()" id="tab-entries">Entries</button>

            <button class="btn btn-secondary" onclick="ShowAssets()" id="tab-assets">Assets</button>
          </div>

          <div class="card pre-scrollable" id='div-entries'>
            <div class="card-body">
              <table class="table ">
                <thead>
                  <tr>
                    <% @entries_table_fieldnames.values.each do |value|  %>
                    <%value.each do |val_index|%>
                    <th scope="col"><%= split_camel_casing(val_index).titleize%></th>
                    <%end%>
                    <%end%>
                  </tr>
                </thead>
                <tbody>
                  <%@entries['items'].each do |entry|%>
                  <tr>
                    <% @entries_table_fieldnames.keys.each do |key|  %>
                    <%@entries_table_fieldnames[key].each do |val_index|%>
                    <td>
                      <%if (val_index=='createdBy' or val_index=='updatedBy') then%>
                      <%if (get_user_by_id(entry[key.to_s][val_index])=='err') then %>
                      Unknown User
                      <%else%>
                      <%= get_user_by_id(entry[key.to_s][val_index])['fields']['name'] %>
                      <%end%>
                      <%else%>
                      <%= entry[key.to_s][val_index] %>
                      <%end%>
                    </td>

                    <%end%>
                    <%end%>
                  </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
          <div class="card pre-scrollable" id="div-assets">
            <div class="card-body">
              <table class="table">
                <thead>
                  <tr>
                    <% @assets_table_fieldnames.values.each do |value|  %>
                    <%value.each do |val_index|%>
                    <%if (val_index=='upload') then%>
                    <%else%>
                    <th scope="col"><%= split_camel_casing(val_index).titleize%></th>
                    <%end%>
                    <%end%>
                    <%end%>
                  </tr>
                </thead>
                <tbody>
                  <%@assets['items'].each do |asset|%>
                  <tr>
                    <% @assets_table_fieldnames.keys.each do |key|  %>
                    <%@assets_table_fieldnames[key].each do |val_index|%>
                    <%if (val_index=='upload') then%>
                    <%else%>
                    <td>
                      <%if (val_index=='fileName') then%>
                      <a href="<%= asset[key.to_s]['upload'] %>"><%= asset[key.to_s][val_index] %></a>
                      <%else%>

                      <%if (val_index=='createdBy' or val_index=='updatedBy') then%>

                      <%if (get_user_by_id(asset[key.to_s][val_index])=='err') then %>
                      Unknown User
                      <%else%>
                      <%= get_user_by_id(asset[key.to_s][val_index])['fields']['name'] %>
                      <%end%>
                      <%else%>
                      <%= asset[key.to_s][val_index] %>
                      <%end%>
                      <%end%>

                    </td>
                    <%end%>
                    <%end%>
                    <%end%>
                  </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
            <br>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<script>

  function ShowEntries(){
    $('#div-assets').hide();
    $('#div-entries').show();
    $('#tab-entries').addClass('active');
    $('#tab-assets').removeClass('active');

  }
  function ShowAssets(){
    $('#div-entries').hide();
    $('#div-assets').show();
    $('#tab-assets').addClass('active');
    $('#tab-entries').removeClass('active');
  }

  $(document).ready( function () {
    $('#div-assets').hide();
  });
</script>

app/views/space_explorers/new.html.erb
<h1>New Space Explorer</h1>

<%= render 'form', space_explorer: @space_explorer %>

<%= link_to 'Back', space_explorers_path %>

app/views/space_explorers/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs'>

      <ul class="nav nav-pills flex-column">
        <%unless get_all_spaces()=='err'%>
        <% get_all_spaces()['items'].each do |entry|%>
        <li class="nav-item">
          
          <a class="nav-link" href="/space_explorers/<%=entry['sys']['id']%>"><%=entry['fields']['title']%></a>
        </li>
        <%end%>

        <%end%>
      </ul>
    </div>
    <div class='col-xl'>
      <div class="card" id='div-main'>
        <div class="card-body">
          <p id="notice"><%= notice %></p>
          <%if get_all_spaces()=='err'%>
            <h6>We're having trouble loading spaces - please try again later</h6>
          <%else%>
          <h1><%=@space['fields']['title'] %></h1>
          <h6><%=@space['fields']['description'] %></h6>

          <div class="btn-group" role="group">
            <button class="btn btn-secondary active" onclick="ShowEntries()" id="tab-entries">Entries</button>

            <button class="btn btn-secondary" onclick="ShowAssets()" id="tab-assets">Assets</button>
          </div>

          <div class="card pre-scrollable" id='div-entries'>
            <div class="card-body">
              <table class="table ">
                <thead>
                  <tr>
                    <% @entries_table_fieldnames.values.each do |value|  %>
                    <%value.each do |val_index|%>
                    <th scope="col"><%= split_camel_casing(val_index).titleize%></th>
                    <%end%>
                    <%end%>
                  </tr>
                </thead>
                <tbody>
                  <%@entries['items'].each do |entry|%>
                  <tr>
                    <% @entries_table_fieldnames.keys.each do |key|  %>
                    <%@entries_table_fieldnames[key].each do |val_index|%>
                    <td>
                      <%if (val_index=='createdBy' or val_index=='updatedBy') then%>
                      <%if (get_user_by_id(entry[key.to_s][val_index])=='err') then %>
                      Unknown User
                      <%else%>
                      <%= get_user_by_id(entry[key.to_s][val_index])['fields']['name'] %>
                      <%end%>
                      <%else%>
                      <%= entry[key.to_s][val_index] %>
                      <%end%>
                    </td>

                    <%end%>
                    <%end%>
                  </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
          <div class="card pre-scrollable" id="div-assets">
            <div class="card-body">
              <table class="table">
                <thead>
                  <tr>
                    <% @assets_table_fieldnames.values.each do |value|  %>
                    <%value.each do |val_index|%>
                    <%if (val_index=='upload') then%>
                    <%else%>
                    <th scope="col"><%= split_camel_casing(val_index).titleize%></th>
                    <%end%>
                    <%end%>
                    <%end%>
                  </tr>
                </thead>
                <tbody>
                  <%@assets['items'].each do |asset|%>
                  <tr>
                    <% @assets_table_fieldnames.keys.each do |key|  %>
                    <%@assets_table_fieldnames[key].each do |val_index|%>
                    <%if (val_index=='upload') then%>
                    <%else%>
                    <td>
                      <%if (val_index=='fileName') then%>
                      <a href="<%= asset[key.to_s]['upload'] %>"><%= asset[key.to_s][val_index] %></a>
                      <%else%>

                      <%if (val_index=='createdBy' or val_index=='updatedBy') then%>

                      <%if (get_user_by_id(asset[key.to_s][val_index])=='err') then %>
                      Unknown User
                      <%else%>
                      <%= get_user_by_id(asset[key.to_s][val_index])['fields']['name'] %>
                      <%end%>
                      <%else%>
                      <%= asset[key.to_s][val_index] %>
                      <%end%>
                      <%end%>

                    </td>
                    <%end%>
                    <%end%>
                    <%end%>
                  </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
            <br>
          </div>
        </div>
        <% end %>
        <!-- <div class="row"> -->
        <%# <%= link_to 'New Space Explorer', new_space_explorer_path %>
        <!-- </div> -->
      </div>
    </div>
  </div>
</div>
<script>

  function ShowEntries(){
    $('#div-assets').hide();
    $('#div-entries').show();
    $('#tab-entries').addClass('active');
    $('#tab-assets').removeClass('active');

  }
  function ShowAssets(){
    $('#div-entries').hide();
    $('#div-assets').show();
    $('#tab-assets').addClass('active');
    $('#tab-entries').removeClass('active');
  }

  $(document).ready( function () {
    $('#div-assets').hide();
  });
</script>